apiVersion: "apiextensions.k8sCRD.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "virtualservices.service.dubbo.apache.org"
spec:
  group: "service.dubbo.apache.org"
  versions:
    - name: "v1alpha1"
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
  scope: "Namespaced"
  names:
    plural: "virtualservices"
    singular: "virtualservice"
    kind: "VirtualService"